#!/usr/bin/env python
# coding: utf-8

# In[5]:


city_to_canton = {
    'Rueras': 'Graubünden', 'Sedrun': 'Graubünden', 'Tavanasa': 'Graubünden',
    'Somvix': 'Graubünden', 'Trun': 'Graubünden', 'Dardin, Casut': 'Graubünden',
    'Obersaxen, St. Joseph': 'Graubünden', 'Waltensburg': 'Graubünden', 'Ilanz': 'Graubünden',
    'Vals, Staumauer Zervreila': 'Graubünden', 'Safien Platz': 'Graubünden', 'Rothenbrunnen': 'Graubünden',
    'St. Martin, Lunschania': 'Graubünden', 'Sagogn': 'Graubünden', 'Flims': 'Graubünden',
    'Trin Mulin': 'Graubünden', 'Trin': 'Graubünden', 'Ausserferrera': 'Graubünden',
    'Nufenen': 'Graubünden', 'Splügen': 'Graubünden', 'Sufers': 'Graubünden',
    'Andeer': 'Graubünden', 'Sils, Nisellas': 'Graubünden', 'Thusis': 'Graubünden',
    'Davos, Frauenkirch': 'Graubünden', 'Davos, Glaris': 'Graubünden', 'Filisur': 'Graubünden',
    'Tiefencastel': 'Graubünden', 'Bivio': 'Graubünden', 'Tinizong-Rona': 'Graubünden',
    'Tinizong': 'Graubünden', 'Riom - Parsonz': 'Graubünden', 'Vaz/Obervaz': 'Graubünden',
    'Sils im Domleschg': 'Graubünden', 'Domat-Ems': 'Graubünden', 'Litzirüti': 'Graubünden',
    'Lüen, Tewald': 'Graubünden', 'Chur, Sand': 'Graubünden', 'Klosters': 'Graubünden',
    'Klosters-Dorf': 'Graubünden', 'Küblis': 'Graubünden', 'Seewis': 'Graubünden',
    'Landquart-Fabriken': 'Graubünden', 'Vadura': 'Graubünden', 'Bad Ragaz': 'St. Gallen',
    'Ragaz': 'St. Gallen', 'Jenins': 'Graubünden', 'Vilters': 'St. Gallen',
    'Wangs, Gaschiels': 'St. Gallen', 'Sevelen': 'St. Gallen', 'Buchs, Waldrand': 'St. Gallen',
    'Buchs, Steig - Aspenhölzli': 'St. Gallen', 'Buchs, Altendorf': 'St. Gallen', 'Grabs, Bannwald': 'St. Gallen',
    'Grabs, Löchli': 'St. Gallen', 'Sennwald': 'St. Gallen', 'Lienz': 'St. Gallen',
    'Oberriet, Blatten': 'St. Gallen', 'Montlingen': 'St. Gallen', 'Heiden, Hinterlochen': 'Appenzell Ausserrhoden',
    'Untereggen, Lochmüli': 'St. Gallen', 'Steinach': 'St. Gallen', 'Schaffhausen': 'Schaffhausen',
    'Neuhausen': 'Schaffhausen', 'Rheinau': 'Zürich', 'Nesslau, unterer Giessenfall': 'St. Gallen',
    'Nesslau, Schneit': 'St. Gallen', 'Krummenau': 'St. Gallen', 'Trempel, Ebnat-Kappel': 'St. Gallen',
    'Ebnat - Kappel': 'St. Gallen', 'Lichtensteig': 'St. Gallen', 'Bütschwil': 'St. Gallen',
    'Mülau bei Bazenheid Kirchberg': 'St. Gallen', 'Glattmüli': 'St. Gallen', 'Bischofszell': 'Thurgau',
    'Rässenaueli': 'Thurgau', 'Urnäsch': 'Appenzell Ausserrhoden', 'St. Gallen': 'St. Gallen',
    'St. Gallen, Sittertal': 'St. Gallen', 'St. Gallen, Grafenau': 'St. Gallen', 'Wittenbach': 'St. Gallen',
    'Schönenberg': 'Zürich', 'Schönenberg an der Thur': 'Thurgau', 'Bürglen': 'Uri',
    'Weinfelden': 'Thurgau', 'Weinfelden, untere Widen': 'Thurgau', 'Matzingen': 'Thurgau',
    'Frauenfeld, Schlossmühlestr.': 'Thurgau', 'Kollbrunn, Gmde. Zell': 'Zürich', 'Sennhof, Illnau-Effretikon': 'Zürich',
    'Neftenbach': 'Zürich', 'Hard, Wülflingen in Winterthur': 'Zürich', 'Freienstein': 'Zürich',
    'Oberuster': 'Zürich', 'Zweidlen': 'Zürich', 'Reckingen': 'Valais', 'Hallau': 'Schaffhausen',
    'Leibstadt': 'Aargau', 'Laufenburg': 'Aargau', 'Bad Säckingen': 'Baden-Württemberg, Germany',
    'Schwörstadt': 'Baden-Württemberg, Germany', 'Schwörstaddt, KW Ryburg-Schw.': 'Baden-Württemberg, Germany',
    'Rheinfelden': 'Aargau', 'Augst': 'Basel-Landschaft', 'Grenzach-Wyhlen': 'Baden-Württemberg, Germany',
    'Birsfelden': 'Basel-Landschaft', 'Gorges de Court': 'Bern', 'Choindez': 'Bern',
    'Undervelier, Blanches-Fontaine': 'Bern', 'Chez Theurillat, Haute-Sorne': 'Bern', 'Soyhières': 'Bern',
    'Laufen': 'Basel-Landschaft', 'Zwingen': 'Basel-Landschaft', 'Nenzlingen': 'Basel-Landschaft',
    'Grellingen': 'Basel-Landschaft', 'Dornach': 'Solothurn', 'Münchenstein': 'Basel-Landschaft',
    'Barrage de Kembs': 'Alsace, France', 'Kembs, Loechle': 'Alsace, France', 'Grimsel, Chessituren': 'Bern',
    'Guttannen, Spitelnollen': 'Bern', 'Grimsel, Sommerloch u.Hospiz': 'Bern', 'Grimsel, Sommerloch, u.Hospiz': 'Bern',
    'Handegg': 'Bern', 'Guttannen, Blatti': 'Bern', 'Innertkirchen, Underürbach': 'Bern',
    'Innertkirchen': 'Bern', 'Underi-Furen, Innertkirchen': 'Bern', 'Hopflauenen': 'Bern',
    'Meiringen, Haselholz': 'Bern', 'Meiringen': 'Bern', 'Schattenhalb': 'Bern', 'Brienz': 'Bern',
    'Grindelwald': 'Bern', 'Lütschental': 'Bern', 'Lauterbrunnen, Stechelberg': 'Bern', 'Saxeten': 'Bern',
    'Wilderswil': 'Bern', 'Interlaken, Kanal': 'Bern', 'Unterseen': 'Bern', 'Kandersteg, Eggeschwand': 'Bern',
    'Kandersteg, Zilfuri': 'Bern', 'Kandersteg, Dorf': 'Bern', 'Inner-Kandergrund': 'Bern', 'Adelboden, Engstligenalp': 'Bern',
    'Reichenbach, Losplatte': 'Bern', 'Adelboden, Moosweid': 'Bern', 'Adelboden': 'Bern', 'Längmad am Thunersee': 'Bern',
    'St. Stephan, Matten': 'Bern', 'St. Stephan': 'Bern', 'Boltigen, Garstatt': 'Bern', 'Weissenburg': 'Bern',
    'Erlenbach': 'Bern', 'Simmenfluh (Wimmis)': 'Bern', 'Thun': 'Bern', 'Thun, Kanal (Uttigenstr.)': 'Bern',
    'Blumenstein': 'Bern', 'Bern, Matte': 'Bern', 'Engehalde': 'Bern', 'Felsenau': 'Bern', 'Buttenried': 'Bern',
    'Innergsteig': 'Bern', 'Lauenen bei Gstaad': 'Bern', 'Gsteig b.Gstaad': 'Bern', "Château d'Oex, Gérignoz": 'Vaud',
    'Montbovon': 'Fribourg', 'Lessoc': 'Fribourg', 'Grandvillard': 'Fribourg', 'Jaun': 'Fribourg', 'Charmey, La Tzintre': 'Fribourg', 'Charmey, Le Perré': 'Fribourg',
    'Broc': 'Fribourg', 'Rossens': 'Fribourg', 'Hauterive': 'Fribourg',
    'Fribourg, Maigrauge': 'Fribourg', 'Fribourg, Oelberg': 'Fribourg', 'Schiffenen': 'Fribourg',
    'Niederried, Radelfingen': 'Bern', 'Aarberg': 'Bern', 'Kallnach': 'Bern',
    'Hagneck': 'Bern', 'La Dernier': 'Vaud', 'Vallorbe': 'Vaud',
    'Les Clées': 'Vaud', 'Montcherand': 'Vaud', 'Orbe': 'Vaud',
    'St.Sulpice': 'Neuchâtel', 'Noiraigue, Le Furcil': 'Neuchâtel', 'Brot-Dessous, Les Moyats': 'Neuchâtel',
    'Boudry, Combe-Garot': 'Neuchâtel', 'Boudry': 'Neuchâtel', 'La Serrière, Neuchâtel': 'Neuchâtel',
    'Sonceboz': 'Bern', 'Péry, Rondchâtel': 'Bern', 'Frinvillier': 'Bern',
    'Biel-Bözingen': 'Bern', 'Bözingen': 'Bern', 'Brügg': 'Bern',
    'Rüderswil': 'Bern', 'Gohlhusbrügg, Lützelflüh': 'Bern', 'Bätterkinden': 'Bern',
    'Utzenstorf': 'Bern', 'Wiler bei Utzenstorf': 'Bern', 'Biberist': 'Solothurn',
    'Derendingen': 'Solothurn', 'Luterbach': 'Solothurn', 'Riedholz': 'Solothurn',
    'Bannwil': 'Bern', 'Oberwynau': 'Bern', 'Schwarzhäusern': 'Bern',
    'Boningen': 'Solothurn', 'Aarburg': 'Aargau', 'Olten': 'Solothurn',
    'Niedergösgen': 'Solothurn', 'Aarau': 'Aargau', 'Auenstein': 'Aargau',
    'Rupperswil': 'Aargau', 'Niederlenz': 'Aargau', 'Schinznach-Dorf': 'Aargau',
    'Villnachern': 'Aargau', 'Döttingen': 'Aargau', 'Klingnau, Gippingen': 'Aargau',
    'Hospental': 'Uri', 'Realp': 'Uri', 'Andermatt': 'Uri',
    'Göschenen': 'Uri', 'Pfaffensprung': 'Uri', 'Wassen, Pfaffensprung': 'Uri',
    'Gurtnellen': 'Uri', 'Bristen': 'Uri', 'Amsteg': 'Uri',
    'Erstfeld, Ripshusen': 'Uri', 'Unterschächen': 'Uri', 'Altdorf': 'Uri',
    'Isenthal': 'Uri', 'Seedorf': 'Uri', 'Bisisthal, Sahli': 'Schwyz',
    'Bisisthal': 'Schwyz', 'Muotathal': 'Schwyz', 'Ibach': 'Schwyz',
    'Steinen, Müliacher': 'Schwyz', 'Beckenried': 'Nidwalden', 'Engelberg, Stalden': 'Obwalden',
    'Engelberg': 'Obwalden', 'Grafenort': 'Obwalden', 'Wolfenschiessen': 'Nidwalden',
    'Wolfenschiessen, Flüglisloo': 'Nidwalden', 'Oberrickenbach': 'Nidwalden', 'Lungern': 'Obwalden',
    'Giswil': 'Obwalden', 'Sachseln, Obflue': 'Obwalden', 'Kerns, Stöckalp': 'Obwalden',
    'Kerns, Wisserlen': 'Obwalden', 'Alpnach, Eichibrücke': 'Obwalden', 'Stansstad, Rotzloch': 'Nidwalden',
    'Luzern': 'Lucerne', 'Wolhusen': 'Lucerne', 'Malters': 'Lucerne',
    'Kriens/Obernau': 'Lucerne', 'Littau': 'Lucerne', 'Emmenbrücke': 'Lucerne',
    'Emmen': 'Lucerne', 'Perlen, Buchrain': 'Lucerne', 'Perlen, Root': 'Lucerne',
    'Unterägeri': 'Zug', 'Neuägeri, Gmde Menzingen': 'Zug', 'Lorzentobel, Nidfuren': 'Zug',
    'Lorzentobel': 'Zug', 'Baar': 'Zug', 'Friesencham, Cham': 'Zug',
    'Hagendorn': 'Zug', 'Bremgarten': 'Aargau', 'Windisch': 'Aargau',
    'Linthal, Ochsenstafel': 'Glarus', 'Linthal, Tierfehd': 'Glarus', 'Linthal': 'Glarus',
    'Linthal, Stachelberg': 'Glarus', 'Braunwald': 'Glarus', 'Rüti, Gmde Glarus Süd': 'Glarus',
    'Diesbach': 'Glarus', 'Hätzingen': 'Glarus', 'Luchsingen': 'Glarus',
    'Leuggelbach': 'Glarus', 'Haslen': 'Glarus', 'Schwanden': 'Glarus',
    'Elm': 'Glarus', 'Matt': 'Glarus', 'Engi (Glarus Süd)': 'Glarus',
    'Engi, Vorderdorf (Glarus Süd)': 'Glarus', 'Engi, Unter Engi': 'Glarus', 'Mitlödi (Glarus Süd)': 'Glarus',
    'Ennenda': 'Glarus', 'Mitlödi, Gmde. Glarus Süd': 'Glarus', 'Ennenda, Alpenbrüggli': 'Glarus',
    'Netstal': 'Glarus', 'Mels': 'St. Gallen', 'Mels, Steigs': 'St. Gallen',
    'Mels, Plons': 'St. Gallen', 'Flums': 'St. Gallen', 'Flums, Rüfi': 'St. Gallen',
    'Töbeli': 'St. Gallen', 'Mols, Tal': 'St. Gallen', 'Oberterzen': 'St. Gallen',
    'Murgtal, Unter Plätz': 'St. Gallen', 'Murg, unterhalb Gödis': 'St. Gallen', 'Murg': 'St. Gallen',
    'Amden, Muslen': 'St. Gallen', 'Rütiberg / Näfels': 'Glarus', 'Näfels': 'Glarus',
    'Niederurnen': 'Glarus', 'Ziegelbrücke': 'Glarus', 'Uznach': 'St. Gallen',
    'Vorderthal, Rempen': 'Schwyz', 'Siebnen': 'Schwyz', 'Galgenen, Vorauen': 'Schwyz',
    'Rüti': 'Zürich', 'Altendorf': 'Schwyz', 'Bäch': 'Schwyz',
    'Schindellegi': 'Schwyz', 'Wollerau': 'Schwyz', 'Zürich': 'Zürich',
    'Wettingen': 'Aargau', 'Baden': 'Aargau', 'Baden, Chappelerhof': 'Aargau',
    'Untersiggenthal, Schiffmüli': 'Aargau', 'Turgi': 'Aargau', 'Untersiggenthal': 'Aargau',
    'Ulrichen, Altstafel': 'Valais', 'Oberwald, St. Niklaus': 'Valais', 'Ulrichen, zum Loch': 'Valais',
    'Münster, Moos': 'Valais', 'Wiler, Münster-Geschinen': 'Valais', 'Grafschaft': 'Valais',
    'Rappental': 'Valais', 'Neubrigg': 'Valais', 'Fieschertal': 'Valais',
    'Fiesch': 'Valais', 'Niederernen': 'Valais', 'Heiligkreuz, Längtal': 'Valais',
    'Heiligkreuz': 'Valais', 'Mörel': 'Valais', 'Bitsch': 'Valais',
    'Bitsch, Biel': 'Valais', 'Mund, In de Fäldu (Gem.Naters)': 'Valais', 'Ried-Brig': 'Valais', 'Brig-Glis': 'Valais', 'Badhalte, Brig-Glis': 'Valais', 'Saas Almagell, Zermeiggern': 'Valais',
    'Saas-Fee, Wichulti': 'Valais', 'Stalden': 'Valais', 'Mossjesee, Zermatt': 'Valais',
    'Zermatt': 'Valais', 'Täsch': 'Valais', 'St. Niklaus': 'Valais',
    'Eisten, VS': 'Valais', 'Törbel, Gappil': 'Valais', 'Stalden, Ackersand': 'Valais',
    'Visperterminen, Chrizji': 'Valais', 'Vispenterminen, Stundhüs': 'Valais', 'Baltschieder': 'Valais',
    'Tscherggen': 'Valais', 'Unterbäch': 'Valais', 'Eischoll': 'Valais',
    'Raron': 'Valais', 'Niedergesteln, Turtig': 'Valais', 'Niedergesteln': 'Valais',
    'Blatten': 'Valais', 'Wiler (Lötschen)': 'Valais', 'Ferden': 'Valais',
    'Steg-Hohtenn': 'Valais', 'Oberems': 'Valais', 'Oberems, Meretschialp': 'Valais',
    'Turtmann, Müllacheren': 'Valais', 'Dalaloch, Leuk-Stadt': 'Valais', 'Chippis': 'Valais',
    'Grimentz-Lona, Val de Moiry': 'Valais', 'Ayer, Mottec': 'Valais', 'Ayer, Vissoie': 'Valais',
    'Croix / Ayent': 'Valais', 'Chamarin / Ayent': 'Valais', 'Icogne': 'Valais',
    'St-Léonard, Mangol': 'Valais', 'St. Léonard': 'Valais', 'Hérémence, Sauterot': 'Valais',
    'Hérémence': 'Valais', 'Bramois': 'Valais', 'Siviez, Cleuson': 'Valais',
    'Savièse': 'Valais', 'Arbaz': 'Valais', 'Vétroz, Péteille': 'Valais',
    'Ardon': 'Valais', 'Balavaud / Ardon': 'Valais', 'Stafel': 'Valais',
    "Z'Mutt": 'Valais', 'Ferpècle': 'Valais', 'Arolla': 'Valais',
    'Riddes': 'Valais', 'Fionnay': 'Valais', 'Isérables': 'Valais',
    'Les Pontets, Riddes': 'Valais', 'Riddes, Pied du Mont': 'Valais', 'Fionnay, Mauvoisin': 'Valais',
    'Riddes, Ecône': 'Valais', 'Leytron': 'Valais', 'Fully': 'Valais',
    'Fully, Les Garettes': 'Valais', 'Champsec': 'Valais', 'Le Châble, Bagnes': 'Valais',
    'Le Châble, Profray, Com.Bagnes': 'Valais', 'Pas-du Lein': 'Valais', 'Vollèges': 'Valais',
    "L'Hospitalet": 'Valais', 'Bourg-St-Pierre, La Delise': 'Valais', 'Liddes': 'Valais',
    'Le Niollet, Champex': 'Valais', 'Orsières': 'Valais', 'Pt. de la Tsi / Liddes': 'Valais',
    'Sembrancher, Les Moulins': 'Valais', 'Martigny-Bourg': 'Valais', 'Martigny-Combe': 'Valais',
    'Le Châtelard': 'Valais', 'Vallorcine': 'Valais', 'Salvan, Alpage de Barberine': 'Valais',
    'Vernayaz': 'Valais', 'Martigny': 'Valais', 'Vernayaz, Miéville': 'Valais',
    'Giétroz du Fond': 'Valais', 'Clusanfe': 'Valais', 'Collonges': 'Valais',
    'Evionnaz, La Rasse': 'Valais', 'Lavey': 'Valais', 'La Peuffeyre': 'Valais',
    'Bex': 'Vaud', 'Le Bévieux': 'Vaud', 'Etrivouez, Grand Paradis': 'Vaud',
    "La Frassenaye, Val d'Jlliez": 'Vaud', 'Monthey': 'Valais', 'Monthey, Les Nants': 'Valais',
    'Vionnaz, Beffeux': 'Valais', 'Les Diablerets, Le Plan': 'Vaud', 'Ormont-Dessous, Le Pont': 'Vaud',
    'Ormont - Dessous, Le Pont': 'Vaud', 'Aigle, En la Douve': 'Vaud', 'Fontanney, Les Farettes': 'Vaud',
    'Les Farettes, Aigle': 'Vaud', 'Vouvry': 'Valais', 'Saint-Gingolph, Vignolles': 'Valais',
    'Veytaux, Chillon': 'Vaud', 'Montreux, Sonzier': 'Vaud', 'Les Planches, Taulan': 'Vaud',
    'Rivaz': 'Vaud', 'Aubonne': 'Vaud', 'Lavigny': 'Vaud',
    'Genève': 'Geneva', 'Veyrier, Iles de Vessy': 'Geneva', 'Russin': 'Geneva',
    'Avully / Chancy': 'Geneva', 'Challex': 'Geneva', 'Les Brenets, La Rançonnière': 'Neuchâtel',
    'Les Planchettes': 'Neuchâtel', 'Echelles de la Mort': 'Neuchâtel', 'Le Noirmont': 'Jura',
    'Bedretto, Ossasco': 'Ticino', 'Motti della Bolla': 'Ticino', 'Airolo': 'Ticino',
    'Cap.dei Morti': 'Ticino', 'Airolo, Launc': 'Ticino', 'Piotta': 'Ticino',
    'Rodi-Fiesso': 'Ticino', 'Prato Leventina, P. di Masc.': 'Ticino', 'Faido': 'Ticino',
    'Dalpe': 'Ticino', 'Lavorgo, Nivo di Chironico': 'Ticino', 'Chironico': 'Ticino',
    'Personico': 'Ticino', 'Ghirone': 'Ticino', 'Olivone': 'Ticino',
    'Biasca': 'Ticino', 'Mesocco, Spina': 'Graubünden', 'Mesocco, Camou': 'Graubünden',
    'Soazza': 'Graubünden', 'Lostallo, Rura': 'Graubünden', 'Piani di Verdabbio': 'Graubünden',
    'Grono, Oltra': 'Graubünden', 'Roveredo': 'Graubünden', 'Giubiasco': 'Ticino',
    'Gordola': 'Ticino', 'Tenero': 'Ticino', 'Piano di Peccia': 'Ticino',
    'Robiei': 'Ticino', 'San Carlo': 'Ticino', 'Broglio, Corsgèla in Lavizarra': 'Ticino',
    'Cavergno': 'Ticino', 'Brissago': 'Ticino', 'Cerentino, Collinasca': 'Ticino',
    'Someo, Giumaglio': 'Ticino', 'Palagnedra': 'Ticino', 'Tegna, Ponte Brolla': 'Ticino',
    'Sonvico': 'Ticino', 'Sigirino (Monteceneri)': 'Ticino', 'Maroggia': 'Ticino',
    'Gabi': 'Valais', 'Gondo, San Marco': 'Valais', 'Gondo, Tannuwald': 'Valais',
    'Poschiavo, Alpe Palü': 'Graubünden', 'Poschiavo, Bernina': 'Graubünden', 'Poschiavo, Cavaglia': 'Graubünden',
    'S. Carlo, Robbia': 'Graubünden', 'San Carlo, Pedecosta': 'Graubünden', 'Campocologno': 'Graubünden',
    'Casaccia': 'Graubünden', 'Plancanin': 'Graubünden', 'Murtaira': 'Graubünden',
    'Promontogno, Gmde. Bregaglia': 'Graubünden', 'Castasegna': 'Graubünden', 'Silvaplana': 'Graubünden',
    'Scuol': 'Graubünden', 'Celerina': 'Graubünden', 'Roseg, Samedan': 'Graubünden', 'Pontresina, Morteratsch': 'Graubünden', 'Samedan': 'Graubünden',
    'Madulain': 'Graubünden', 'Susch': 'Graubünden', 'Lavin': 'Graubünden',
    'Guarda-Giarsun Gmd. Scuol': 'Graubünden', 'Ardez': 'Graubünden', 'Tarasp': 'Graubünden',
    'Strada': 'Graubünden', 'Samnaun-Compatch': 'Graubünden', 'Zernez': 'Graubünden',
    'Martina': 'Graubünden', 'Sta.Maria': 'Graubünden', 'Müstair/Chasseras': 'Graubünden',
    'Mühleberg': 'Bern', 'Däniken': 'Solothurn', 'Wald': 'Zürich',
    'Rüti': 'Zürich', 'Zürich': 'Zürich', 'Winterthur': 'Zürich',
    'Schaffhausen': 'Schaffhausen', 'Aarau': 'Aargau', 'Olten': 'Solothurn',
    'Baden': 'Aargau', 'Rheinfelden': 'Aargau', 'Basel': 'Basel-Stadt',
    'Liestal': 'Basel-Landschaft', 'Delémont': 'Jura', 'Biel/Bienne': 'Bern',
    'Neuchâtel': 'Neuchâtel', 'Lausanne': 'Vaud', 'Fribourg': 'Fribourg',
    'Sion': 'Valais', 'Bellinzona': 'Ticino', 'Chur': 'Graubünden',
    'St. Gallen': 'St. Gallen', 'Luzern': 'Lucerne', 'Zug': 'Zug',
    'Thun': 'Bern', 'Köniz': 'Bern', 'La Chaux-de-Fonds': 'Neuchâtel',
    'Schwyz': 'Schwyz', 'Yverdon-les-Bains': 'Vaud', 'Nyon': 'Vaud',
    'Uster': 'Zürich', 'Wetzikon': 'Zürich', 'Bülach': 'Zürich',
    'Dietikon': 'Zürich', 'Horgen': 'Zürich', 'Kloten': 'Zürich',
    'Meilen': 'Zürich', 'Wädenswil': 'Zürich', 'Affoltern': 'Zürich',
    'Andelfingen': 'Zürich', 'Dielsdorf': 'Zürich', 'Hinwil': 'Zürich',
    'Pfyn': 'Thurgau', 'Weinfelden': 'Thurgau', 'Frauenfeld': 'Thurgau',
    'Kreuzlingen': 'Thurgau', 'Arbon': 'Thurgau', 'Romanshorn': 'Thurgau',
    'Amriswil': 'Thurgau', 'Gossau': 'St. Gallen', 'Wil': 'St. Gallen',
    'Herisau': 'Appenzell Ausserrhoden', 'Appenzell': 'Appenzell Innerrhoden', 'Altstätten': 'St. Gallen',
    'Rorschach': 'St. Gallen', 'Rapperswil-Jona': 'St. Gallen', 'Glarus': 'Glarus',
    'Näfels': 'Glarus', 'Schwanden': 'Glarus', 'Altdorf': 'Uri',
    'Brunnen': 'Schwyz', 'Goldau': 'Schwyz', 'Einsiedeln': 'Schwyz',
    'Schübelbach': 'Schwyz', 'Arth': 'Schwyz', 'Küssnacht': 'Schwyz',
    'Schübelbach': 'Schwyz', 'Zug': 'Zug', 'Baar': 'Zug',
    'Cham': 'Zug', 'Hünenberg': 'Zug', 'Steinhausen': 'Zug',
    'Rotkreuz': 'Zug', 'Alpnach': 'Obwalden', 'Giswil': 'Obwalden',
    'Kerns': 'Obwalden', 'Lungern': 'Obwalden', 'Sachseln': 'Obwalden',
    'Sarnen': 'Obwalden', 'Stans': 'Nidwalden', 'Buochs': 'Nidwalden',
    'Beckenried': 'Nidwalden', 'Hergiswil': 'Nidwalden', 'Ennetbürgen': 'Nidwalden',
    'Stansstad': 'Nidwalden', 'Oberdorf': 'Nidwalden', 'Dallenwil': 'Nidwalden',
    'Wolfenschiessen': 'Nidwalden', 'Engelberg': 'Obwalden', 'Luzern': 'Lucerne',
    'Emmen': 'Lucerne', 'Kriens': 'Lucerne', 'Horw': 'Lucerne',
    'Ebikon': 'Lucerne', 'Kriens': 'Lucerne', 'Hergiswil': 'Nidwalden',
    'Ennetmoos': 'Nidwalden', 'Sarnen': 'Obwalden', 'Luzern': 'Lucerne',
    'Zofingen': 'Aargau', 'Aarau': 'Aargau', 'Brugg': 'Aargau',
    'Rheinfelden': 'Aargau', 'Baden': 'Aargau', 'Wettingen': 'Aargau',
    'Bülach': 'Zürich', 'Winterthur': 'Zürich', 'Uster': 'Zürich',
    'Zürich': 'Zürich', 'Zug': 'Zug', 'Chur': 'Graubünden',
    'Sargans': 'St. Gallen', 'Glarus': 'Glarus', 'Schwyz': 'Schwyz',
    'Altdorf': 'Uri', 'Flüelen': 'Uri', 'Schattdorf': 'Uri',
    'Andermatt': 'Uri', 'Bürglen': 'Uri', 'Schwyz': 'Schwyz',
    'Freienbach': 'Schwyz', 'Lachen': 'Schwyz', 'Pfäffikon': 'Schwyz',
    'Zug': 'Zug', 'Baar': 'Zug', 'Cham': 'Zug',
    'Hünenberg': 'Zug', 'Steinhausen': 'Zug', 'Risch': 'Zug',
    'Rotkreuz': 'Zug', 'Neuheim': 'Zug', 'Unterägeri': 'Zug',
    'Oberägeri': 'Zug', 'Menzingen': 'Zug', 'Walchwil': 'Zug',
    'Zug': 'Zug', 'Sion': 'Valais', 'Sierre': 'Valais',
    'Monthey': 'Valais', 'Martigny': 'Valais', 'Visp': 'Valais',
    'Brig-Glis': 'Valais', 'Leuk': 'Valais', 'Natters': 'Valais',
    'Turtmann': 'Valais', 'Gampel': 'Valais', 'Raron': 'Valais',
    'Visp': 'Valais', 'Leukerbad': 'Valais', 'Riederalp': 'Valais',
    'Fiesch': 'Valais', 'Bettmeralp': 'Valais', 'Zermatt': 'Valais',
    'Täsch': 'Valais', 'Grächen': 'Valais', 'Saas-Fee': 'Valais',
    'Saas-Grund': 'Valais', 'Stalden': 'Valais', 'Visperterminen': 'Valais',
    'Veysonnaz': 'Valais', 'Nendaz': 'Valais', 'Siviez': 'Valais',
    'Haute-Nendaz': 'Valais', 'Evolène': 'Valais', 'Grimentz': 'Valais',
    'Zinal': 'Valais', 'Arolla': 'Valais', 'Lausanne': 'Vaud',
    'Vevey': 'Vaud', 'Montreux': 'Vaud', 'Yverdon-les-Bains': 'Vaud',
    'Nyon': 'Vaud', 'Morges': 'Vaud', 'Renens': 'Vaud',
    'Pully': 'Vaud', 'Gland': 'Vaud', 'Rolle': 'Vaud',
    'Cossonay': 'Vaud', 'Morges': 'Vaud', 'Rolle': 'Vaud',
    'Echallens': 'Vaud', 'Orbe': 'Vaud', 'Lausanne': 'Vaud',
    'Fribourg': 'Fribourg', 'Bulle': 'Fribourg', 'Estavayer-le-Lac': 'Fribourg',
    'Murten': 'Fribourg', 'Avenches': 'Fribourg', 'Düdingen': 'Fribourg', 'Granges-Paccot': 'Fribourg', 'Villars-sur-Glâne': 'Fribourg',
    'Marly': 'Fribourg', 'Givisiez': 'Fribourg', 'Murten': 'Fribourg',
    'Kerzers': 'Fribourg', 'Belfaux': 'Fribourg', 'Courtepin': 'Fribourg',
    'Schmitten': 'Fribourg', 'Gurmels': 'Fribourg', 'Bulle': 'Fribourg',
    'Romont': 'Fribourg', 'Châtel-Saint-Denis': 'Fribourg', 'Fribourg': 'Fribourg',
    'Bern': 'Bern', 'Thun': 'Bern', 'Biel/Bienne': 'Bern',
    'Burgdorf': 'Bern', 'Langenthal': 'Bern', 'Interlaken': 'Bern',
    'Münsingen': 'Bern', 'Worb': 'Bern', 'Belp': 'Bern',
    'Lyss': 'Bern', 'Moutier': 'Bern', 'Langnau im Emmental': 'Bern',
    'Spiez': 'Bern', 'Zollikofen': 'Bern', 'Steffisburg': 'Bern',
    'Köniz': 'Bern', 'Ostermundigen': 'Bern', 'Ittigen': 'Bern',
    'Muri bei Bern': 'Bern', 'Kehrsatz': 'Bern', 'Münsingen': 'Bern',
    'Rubigen': 'Bern', 'Thun': 'Bern', 'Zäziwil': 'Bern',
    'Bern': 'Bern', 'Brügg': 'Bern', 'Lyss': 'Bern',
    'Worben': 'Bern', 'Biel/Bienne': 'Bern', 'Grenchen': 'Solothurn',
    'Olten': 'Solothurn', 'Solothurn': 'Solothurn', 'Zuchwil': 'Solothurn',
    'Biberist': 'Solothurn', 'Derendingen': 'Solothurn', 'Gerlafingen': 'Solothurn',
    'Langendorf': 'Solothurn', 'Oberdorf': 'Solothurn', 'Oensingen': 'Solothurn',
    'Balsthal': 'Solothurn', 'Bettlach': 'Solothurn', 'Subingen': 'Solothurn',
    'Bellach': 'Solothurn', 'Schönenwerd': 'Solothurn', 'Niederbipp': 'Bern',
    'Murgenthal': 'Aargau', 'Oftringen': 'Aargau', 'Aarburg': 'Aargau',
    'Zofingen': 'Aargau', 'Reiden': 'Lucerne', 'Sursee': 'Lucerne',
    'Ettiswil': 'Lucerne', 'Willisau': 'Lucerne', 'Wolhusen': 'Lucerne',
    'Entlebuch': 'Lucerne', 'Malters': 'Lucerne', 'Emmen': 'Lucerne',
    'Ebikon': 'Lucerne', 'Horw': 'Lucerne', 'Kriens': 'Lucerne',
    'Hochdorf': 'Lucerne', 'Eschenbach': 'Lucerne', 'Baar': 'Zug',
    'Cham': 'Zug', 'Hünenberg': 'Zug', 'Steinhausen': 'Zug',
    'Rotkreuz': 'Zug', 'Zug': 'Zug', 'Sion': 'Valais',
    'Sierre': 'Valais', 'Monthey': 'Valais', 'Martigny': 'Valais',
    'Visp': 'Valais', 'Brig-Glis': 'Valais', 'Leuk': 'Valais',
    'Natters': 'Valais', 'Turtmann': 'Valais', 'Gampel': 'Valais',
    'Raron': 'Valais', 'Visp': 'Valais', 'Leukerbad': 'Valais',
    'Riederalp': 'Valais', 'Fiesch': 'Valais', 'Bettmeralp': 'Valais',
    'Zermatt': 'Valais', 'Täsch': 'Valais', 'Grächen': 'Valais',
    'Saas-Fee': 'Valais', 'Saas-Grund': 'Valais', 'Stalden': 'Valais',
    'Visperterminen': 'Valais', 'Veysonnaz': 'Valais', 'Nendaz': 'Valais',
    'Siviez': 'Valais', 'Haute-Nendaz': 'Valais', 'Evolène': 'Valais',
    'Grimentz': 'Valais', 'Zinal': 'Valais', 'Arolla': 'Valais',
    'Lausanne': 'Vaud', 'Vevey': 'Vaud', 'Montreux': 'Vaud',
    'Yverdon-les-Bains': 'Vaud', 'Nyon': 'Vaud', 'Morges': 'Vaud',
    'Renens': 'Vaud', 'Pully': 'Vaud', 'Gland': 'Vaud',
    'Rolle': 'Vaud', 'Cossonay': 'Vaud', 'Morges': 'Vaud',
    'Rolle': 'Vaud', 'Echallens': 'Vaud', 'Orbe': 'Vaud',
    'Lausanne': 'Vaud', 'Fribourg': 'Fribourg', 'Bulle': 'Fribourg',
    'Estavayer-le-Lac': 'Fribourg', 'Murten': 'Fribourg', 'Avenches': 'Fribourg',
    'Düdingen': 'Fribourg', 'Granges-Paccot': 'Fribourg', 'Villars-sur-Glâne': 'Fribourg',
    'Marly': 'Fribourg', 'Givisiez': 'Fribourg', 'Murten': 'Fribourg',
    'Kerzers': 'Fribourg', 'Belfaux': 'Fribourg', 'Courtepin': 'Fribourg',
    'Schmitten': 'Fribourg', 'Gurmels': 'Fribourg', 'Bulle': 'Fribourg',
    'Romont': 'Fribourg', 'Châtel-Saint-Denis': 'Fribourg', 'Fribourg': 'Fribourg',
    'Bern': 'Bern', 'Thun': 'Bern', 'Biel/Bienne': 'Bern',
    'Burgdorf': 'Bern', 'Langenthal': 'Bern', 'Interlaken': 'Bern',
    'Münsingen': 'Bern', 'Worb': 'Bern', 'Belp': 'Bern',
    'Lyss': 'Bern', 'Moutier': 'Bern', 'Langnau im Emmental': 'Bern',
    'Spiez': 'Bern', 'Zollikofen': 'Bern', 'Steffisburg': 'Bern',
    'Köniz': 'Bern', 'Ostermundigen': 'Bern', 'Ittigen': 'Bern',
    'Muri bei Bern': 'Bern', 'Kehrsatz': 'Bern', 'Münsingen': 'Bern',
    'Rubigen': 'Bern', 'Thun': 'Bern', 'Zäziwil': 'Bern',
    'Bern': 'Bern', 'Brügg': 'Bern', 'Lyss': 'Bern',
    'Worben': 'Bern', 'Biel/Bienne': 'Bern', 'Grenchen': 'Solothurn',
    'Olten': 'Solothurn', 'Solothurn': 'Solothurn', 'Zuchwil': 'Solothurn',
    'Biberist': 'Solothurn', 'Derendingen': 'Solothurn', 'Gerlafingen': 'Solothurn',
    'Langendorf': 'Solothurn', 'Oberdorf': 'Solothurn', 'Oensingen': 'Solothurn',
    'Balsthal': 'Solothurn', 'Bettlach': 'Solothurn', 'Subingen': 'Solothurn',
    'Bellach': 'Solothurn', 'Schönenwerd': 'Solothurn', 'Niederbipp': 'Bern',
    'Murgenthal': 'Aargau', 'Oftringen': 'Aargau', 'Aarburg': 'Aargau',
    'Zofingen': 'Aargau', 'Reiden': 'Lucerne', 'Sursee': 'Lucerne',
    'Ettiswil': 'Lucerne', 'Willisau': 'Lucerne', 'Wolhusen': 'Lucerne',
    'Entlebuch': 'Lucerne', 'Malters': 'Lucerne', 'Emmen': 'Lucerne',
    'Ebikon': 'Lucerne', 'Horw': 'Lucerne', 'Kriens': 'Lucerne',
    'Hochdorf': 'Lucerne', 'Eschenbach': 'Lucerne', 'Baar': 'Zug',
    'Cham': 'Zug', 'Hünenberg': 'Zug', 'Steinhausen': 'Zug',
    'Rotkreuz': 'Zug', 'Zug': 'Zug', 'Cham': 'Zug', 'Hünenberg': 'Zug', 'Steinhausen': 'Zug',
    'Rotkreuz': 'Zug', 'Neuheim': 'Zug', 'Unterägeri': 'Zug',
    'Oberägeri': 'Zug', 'Menzingen': 'Zug', 'Walchwil': 'Zug',
    'Sion': 'Valais', 'Sierre': 'Valais', 'Monthey': 'Valais',
    'Martigny': 'Valais', 'Visp': 'Valais', 'Brig-Glis': 'Valais',
    'Leuk': 'Valais', 'Natters': 'Valais', 'Turtmann': 'Valais',
    'Gampel': 'Valais', 'Raron': 'Valais', 'Leukerbad': 'Valais',
    'Riederalp': 'Valais', 'Fiesch': 'Valais', 'Bettmeralp': 'Valais',
    'Zermatt': 'Valais', 'Täsch': 'Valais', 'Grächen': 'Valais',
    'Saas-Fee': 'Valais', 'Saas-Grund': 'Valais', 'Stalden': 'Valais',
    'Visperterminen': 'Valais', 'Veysonnaz': 'Valais', 'Nendaz': 'Valais',
    'Siviez': 'Valais', 'Haute-Nendaz': 'Valais', 'Evolène': 'Valais',
    'Grimentz': 'Valais', 'Zinal': 'Valais', 'Arolla': 'Valais',
    'Lausanne': 'Vaud', 'Vevey': 'Vaud', 'Montreux': 'Vaud',
    'Yverdon-les-Bains': 'Vaud', 'Nyon': 'Vaud', 'Morges': 'Vaud',
    'Renens': 'Vaud', 'Pully': 'Vaud', 'Gland': 'Vaud',
    'Rolle': 'Vaud', 'Cossonay': 'Vaud', 'Echallens': 'Vaud',
    'Orbe': 'Vaud', 'Fribourg': 'Fribourg', 'Bulle': 'Fribourg',
    'Estavayer-le-Lac': 'Fribourg', 'Murten': 'Fribourg', 'Avenches': 'Fribourg',
    'Düdingen': 'Fribourg', 'Granges-Paccot': 'Fribourg', 'Villars-sur-Glâne': 'Fribourg',
    'Marly': 'Fribourg', 'Givisiez': 'Fribourg', 'Kerzers': 'Fribourg',
    'Belfaux': 'Fribourg', 'Courtepin': 'Fribourg', 'Schmitten': 'Fribourg',
    'Gurmels': 'Fribourg', 'Romont': 'Fribourg', 'Châtel-Saint-Denis': 'Fribourg',
    'Bern': 'Bern', 'Thun': 'Bern', 'Biel/Bienne': 'Bern',
    'Burgdorf': 'Bern', 'Langenthal': 'Bern', 'Interlaken': 'Bern',
    'Münsingen': 'Bern', 'Worb': 'Bern', 'Belp': 'Bern',
    'Lyss': 'Bern', 'Moutier': 'Bern', 'Langnau im Emmental': 'Bern',
    'Spiez': 'Bern', 'Zollikofen': 'Bern', 'Steffisburg': 'Bern',
    'Köniz': 'Bern', 'Ostermundigen': 'Bern', 'Ittigen': 'Bern',
    'Muri bei Bern': 'Bern', 'Kehrsatz': 'Bern', 'Rubigen': 'Bern',
    'Zäziwil': 'Bern', 'Brügg': 'Bern', 'Worben': 'Bern',
    'Grenchen': 'Solothurn', 'Olten': 'Solothurn', 'Solothurn': 'Solothurn',
    'Zuchwil': 'Solothurn', 'Biberist': 'Solothurn', 'Derendingen': 'Solothurn',
    'Gerlafingen': 'Solothurn', 'Langendorf': 'Solothurn', 'Oberdorf': 'Solothurn',
    'Oensingen': 'Solothurn', 'Balsthal': 'Solothurn', 'Bettlach': 'Solothurn',
    'Subingen': 'Solothurn', 'Bellach': 'Solothurn', 'Schönenwerd': 'Solothurn',
    'Niederbipp': 'Bern', 'Murgenthal': 'Aargau', 'Oftringen': 'Aargau',
    'Aarburg': 'Aargau', 'Zofingen': 'Aargau', 'Reiden': 'Lucerne',
    'Sursee': 'Lucerne', 'Ettiswil': 'Lucerne', 'Willisau': 'Lucerne',
    'Wolhusen': 'Lucerne', 'Entlebuch': 'Lucerne', 'Malters': 'Lucerne',
    'Emmen': 'Lucerne', 'Ebikon': 'Lucerne', 'Horw': 'Lucerne',
    'Kriens': 'Lucerne', 'Hochdorf': 'Lucerne', 'Eschenbach': 'Lucerne',
    'Baar': 'Zug', 'Cham': 'Zug', 'Hünenberg': 'Zug',
    'Steinhausen': 'Zug', 'Rotkreuz': 'Zug', 'Neuheim': 'Zug',
    'Unterägeri': 'Zug', 'Oberägeri': 'Zug', 'Menzingen': 'Zug',
    'Walchwil': 'Zug', 'Zug': 'Zug', 'Neuheim': 'Zug'
}


# In[ ]:




